# configme manifest for yelmox.
package = "yelmox"
deps = [
    "fesm-utils:stable",
    "fesm-utils/utils",
    "coordinates:stable",
    "yelmo:stable",
    "FastIsostasy:stable",
    "rembo1:stable",
]
