#!/bin/bash
#SBATCH --qos=<QOS>
#SBATCH --partition=<PARTITION>
#SBATCH --time=<WALL>
#SBATCH --job-name=<JOBNAME>
#SBATCH --account=<ACCOUNT>
#SBATCH --output=./out.out
#SBATCH --error=./out.err
#SBATCH --mem=30Gb
<EMAILSECTION>

<OMPSECTION>

ulimit -s unlimited
#ulimit -c unlimited
#ulimit -s unlimited
#ulimit -d unlimited
#ulimit -m unlimited
ulimit -v unlimited
#ulimit -f unlimited
ulimit -a

# Run the job
srun <CMD> 
