#!/usr/bin/env bash
# Builds libyelmox_marshelf_c_api.so from libs/yelmox_marshelf_c_api.f90.
#
# Not wired into the Makefile: the top-level Makefile is generated by
# `configme` (gitignored, regenerated on every `configme config yelmox`),
# and this target isn't part of configme's own template -- adding it there
# is a separate, out-of-repo change. Run this script directly instead,
# after `configme install yelmox` / `make yelmox_esm` has already built
# yelmox's usual dependencies (needs $(yelmox_libs)'s .o files to exist).
#
# Usage: from the yelmox root (or a worktree of it), with the same
# compiler module loaded that built yelmox_esm.x:
#   module load intel-oneapi-compilers/2024.1.0   # or your machine's equivalent
#   ./libs/build_marshelf_c_api.sh
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root

FC=${FC:-ifx}
FFLAGS="-Ofast -march=znver2 -traceback -fPIC -no-wrap-margin"
OBJDIR=libyelmox/include
INC="-module $OBJDIR -L$OBJDIR -Ifesm-utils/include-serial -Ifesm-utils/lis/lis-serial/include -IFastIsostasy/libisostasy/include -Iyelmo/libyelmo/include"

# The .o files marine_shelf.f90 itself was built into as part of `make yelmox_esm`
# (yelmox_libs in config/Makefile_yelmox.mk) -- reused here rather than duplicated,
# so this script and the Makefile target never drift apart on what marine_shelf.o
# was actually compiled with.
YELMOX_LIBS=$(awk '/^yelmox_libs/{f=1} f{print} /^$/{if(f)exit}' config/Makefile_yelmox.mk \
  | grep -oE '\$\(objdir\)/[A-Za-z0-9_]+\.o' | sed "s#\$(objdir)#$OBJDIR#")

for f in $YELMOX_LIBS; do
  [ -f "$f" ] || { echo "Missing $f -- run 'make yelmox_esm' first." >&2; exit 1; }
done

$FC -shared -fPIC $FFLAGS $INC -c -o "$OBJDIR/yelmox_marshelf_c_api.o" libs/yelmox_marshelf_c_api.f90

# NOTE: deliberately not linking $(LIB_LIS)/$(LIB_FFTW) -- fesm-utils' fftw-serial
# static lib here was not built with -fPIC, and marine_shelf.f90 needs neither
# a linear solver nor an FFT. See the equivalent comment in the Makefile target
# this mirrors (Makefile: yelmox_marshelf_c_api) for the full explanation.
$FC -shared -fPIC $FFLAGS $INC \
  -o "$OBJDIR/libyelmox_marshelf_c_api.so" \
  "$OBJDIR/yelmox_marshelf_c_api.o" $YELMOX_LIBS \
  -Lyelmo/libyelmo/include -lyelmo \
  -LFastIsostasy/libisostasy/include -lisostasy \
  -Lfesm-utils/include-serial -lfesmutils \
  -Lyelmo/FastHydrology/include -lfasthydro \
  -Lyelmo/elsa/libelsa/include -lelsa \
  -Lyelmo/tracer/libtracer/include -ltracer \
  $(nf-config --flibs 2>/dev/null || echo "-L/albedo/soft/sw/spack-sw/netcdf-fortran/4.5.4-lzqfsg3/lib -lnetcdff -L/albedo/soft/sw/spack-sw/netcdf-c/4.8.1-5ewdrxn/lib -lnetcdf") \
  -Wl,-zmuldefs

echo
echo "    $OBJDIR/libyelmox_marshelf_c_api.so is ready."
echo
